language: haskell

ghc:
    - "7.6"
    - "7.8"
    - "7.10"

install:
    - ghc --version
    - cabal --version
    - cabal install hspec doctest cabal-meta cabal-src
    - cabal-meta install --force-reinstalls

script: mega-sdist --test
