language: haskell

ghc:
    - 7.4
    - 7.6
    - 7.8

install:
    - ghc --version
    - cabal --version
    - cabal install hspec doctest HTTP cabal-meta cabal-src
    - cabal-meta install --force-reinstalls

script: mega-sdist --test
