sudo: false

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-1.22
            - ghc-7.6.3
            - ghc-7.8.4
            - ghc-7.10.1
            - ghc-7.10.2

env:
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.1
 - GHCVER=7.10.2

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$HOME/.cabal/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

script:
 - cabal install --run-tests --enable-benchmarks --force-reinstalls wai-extra ./monad-logger ./wai-logger-prefork ./wai-logger ./date-cache ./fast-logger
